[versions]
accompanist-systemuicontroller = "0.36.0"
activity-compose = "1.12.1"
agp = "8.11.0"
androidx-junit = "1.3.0"
apollo-runtime = "4.3.3"
compose-bom = "2025.12.00"
core-ktx = "1.17.0"
credentials = "1.6.0-beta03"
datastore-preferences = "1.2.0"
espresso-core = "3.7.0"
junit = "6.0.1"
junit-version = "4.13.2"
kotest-runner-junit5 = "6.0.7"
kotlin = "2.3.0"
kotlin-result = "2.1.0"
ktor = "3.3.3"
lifecycle-runtime-ktx = "2.10.0"
lifecycle-viewmodel-compose = "2.10.0"
logback-classic = "1.5.21"
navigation-compose = "2.9.6"
play-services-identity-credentials = "16.0.0-alpha08"
security-crypto = "1.1.0"
ksp = "2.2.21-2.0.4"
kotest = "6.0.7"
fastkrypto = "0.1.2"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo-runtime" }
bcs = { module = "xyz.mcxross.bcs:bcs", version = "0.1.3" }
bitcoinj-core = { module = "org.bitcoinj:bitcoinj-core", version = "0.17" }
junit = { module = "junit:junit", version.ref = "junit-version" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest-runner-junit5" }
kotlin-result = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "kotlin-result" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version = "2.2.0" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.2" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
play-services-identity-credentials = { group = "com.google.android.gms", name = "play-services-identity-credentials", version.ref = "play-services-identity-credentials" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions-core =  { module = "io.kotest:kotest-assertions-core", version.ref = "kotest"}
fastkrypto = { module = "xyz.mcxross.fastkrypto:fastkrypto", version.ref = "fastkrypto" }
fastkrypto-android = { module = "xyz.mcxross.fastkrypto:fastkrypto-android", version.ref = "fastkrypto" }
fastkrypto-jvm = { module = "xyz.mcxross.fastkrypto:fastkrypto-jvm", version.ref = "fastkrypto" }
fastkrypto-iosarm64 = { module = "xyz.mcxross.fastkrypto:fastkrypto-iosarm64", version.ref = "fastkrypto" }
fastkrypto-iosx64 = { module = "xyz.mcxross.fastkrypto:fastkrypto-iosx64", version.ref = "fastkrypto" }
fastkrypto-iossimulatorarm64 = { module = "xyz.mcxross.fastkrypto:fastkrypto-iossimulatorarm64", version.ref = "fastkrypto" }
fastkrypto-macosarm64 = { module = "xyz.mcxross.fastkrypto:fastkrypto-macosarm64", version.ref = "fastkrypto" }
fastkrypto-macosx64 = { module = "xyz.mcxross.fastkrypto:fastkrypto-macosx64", version.ref = "fastkrypto" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
apollo-graphql = { id = "com.apollographql.apollo", version.ref = "apollo-runtime" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotest = { id = "io.kotest", version.ref = "kotest" }
